### ISSUE TITLE
Terminator vulnerability

### ISSUE THREAD

**Issue by prestonhashworth** [notnotnotswipez/TerminatorNPC#3]
Is there a config command to make terminator entities vulnerable, perhaps through an API call to the Citizens plugin?

**Comment by Adamiok** [comment]
I have linked a pr to fix your issue. As far as I understand, this is what you are trying to achieve: make the citizens nps vulnerable.

If you meant something else (eg. add a config option to allow you to choose if they are vulnerable), then please let me know,
